name: production build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and push
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: get dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: clone package.json
        run: cp package.json ./build

      - name: push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "build: ({sha}) {msg}"