name: Deploy to VPS via SSH

on:
  push:
    branches: [ main ]

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH auth
        run: |
          ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@${{ secrets.VPS_HOST }} 'echo "SSH OK"'

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa \
              -o StrictHostKeyChecking=no \
              deploy@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            cd /var/www/jays.pics
            npm install
            npx prisma migrate deploy
            npx prisma generate
            npm run build
            pm2 reload jays-pics
          EOF