name: Deploy to VPS via SSH

on:
  push:
    branches: [ main ]

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load deploy key into SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add VPS to known_hosts
        run: |
            ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh deploy@${{ secrets.VPS_HOST }} << 'EOF'
            npm install
            npx prisma migrate deploy
            npx prisma generate
            npm run build
            pm2 reload jays-pics 
          EOF